title: bymfd
subtitle: Kendi halinde developer
description: Projelerim ve kendim hakkımda bilgiler verdiğim basit ama etkili web sitem
url: 'bymfd.github.io'
baseurl: 'bymfd.github.io'
urls:
  - text: Hakkımda
    url: /about
  - text: Blog
    url: /blog
author_logo: profile.png
author: bymfd
author_bio: >-
  Merhaba ben Mevlüt Furkan Demir ,Düşünen, uygulamaya çalışan ,elinden
  geldiğince özgür yazılımlarla vakit harcamakla meşgul biriyim
author_email: frukolosko@gmail.com
author_location: Türkiye
author_website_url: bymfd.github.io
author_education_details:
  - college_logo: s.jpeg
    college_name: Selçuk Üniversitesi
    college_url: ktun.edu.tr
    college_degree: bilgisayar programcılığı
    description: Bilgisayar teknolojileri
    visibility: 'true'
author_work_experiences_details:
    exp.company_url: selcuk.edu.tr
    visibility: 'true'
twitter_username: frukolosko
github_username: bymfd
telegram_username: frukolosko
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: ''
show_author_work_experiences: 'true'
show_author_education_details: 'true'
show_author_project_details: 'true'
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
